name: Pipeline QA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api-k6:
  - name: Adicionar chave pública k6
  run: |
    curl -fsSL https://dl.k6.io/key.gpg | sudo tee /usr/share/keyrings/k6-archive-keyring.gpg > /dev/null

    - name: Adicionar repositório k6 usando signed-by
  run: |
    echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list

     - name: Atualizar e instalar k6
  run: |
    sudo apt-get update
    sudo apt-get install -y k6

  
  steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar K6
        run: |
         sudo snap install k6

      - name: Executar testes de performance
        run: k6 run k6/loadtest.js

  test-web-playwright:
    name: Testes E2E com Playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Instalar browsers do Playwright
        run: npx playwright install --with-deps

      - name: Executar testes E2E
        run: npx playwright test

  test-mobile-appium:
    name: Testes Mobile com Appium
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Instalar Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Iniciar Appium
        run: nohup appium > appium.log 2>&1 &

      - name: Verificar arquivos na pasta mobile-tests
        run: ls -la ./mobile-tests

      - name: Executar testes mobile
        run: npx wdio run ./mobile-tests/wdio.conf.js

